// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_SERVERLOGIN11_MQTT_H_
#define FLATBUFFERS_GENERATED_SERVERLOGIN11_MQTT_H_

#include "flatbuffers/flatbuffers.h"

namespace Mqtt {

struct testtable;

struct test2;

struct testtable FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_USER = 4,
    VT_PASS = 6
  };
  const flatbuffers::String *user() const { return GetPointer<const flatbuffers::String *>(VT_USER); }
  const flatbuffers::String *pass() const { return GetPointer<const flatbuffers::String *>(VT_PASS); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_USER) &&
           verifier.Verify(user()) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_PASS) &&
           verifier.Verify(pass()) &&
           verifier.EndTable();
  }
};

struct testtableBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_user(flatbuffers::Offset<flatbuffers::String> user) { fbb_.AddOffset(testtable::VT_USER, user); }
  void add_pass(flatbuffers::Offset<flatbuffers::String> pass) { fbb_.AddOffset(testtable::VT_PASS, pass); }
  testtableBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  testtableBuilder &operator=(const testtableBuilder &);
  flatbuffers::Offset<testtable> Finish() {
    auto o = flatbuffers::Offset<testtable>(fbb_.EndTable(start_, 2));
    return o;
  }
};

inline flatbuffers::Offset<testtable> Createtesttable(flatbuffers::FlatBufferBuilder &_fbb,
   flatbuffers::Offset<flatbuffers::String> user = 0,
   flatbuffers::Offset<flatbuffers::String> pass = 0) {
  testtableBuilder builder_(_fbb);
  builder_.add_pass(pass);
  builder_.add_user(user);
  return builder_.Finish();
}

struct test2 FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_HOST = 4,
    VT_PORT = 6,
    VT_TOPIC = 8,
    VT_AUTH = 10,
    VT_NAME = 12
  };
  int64_t host() const { return GetField<int64_t>(VT_HOST, 0); }
  int32_t port() const { return GetField<int32_t>(VT_PORT, 0); }
  const flatbuffers::String *topic() const { return GetPointer<const flatbuffers::String *>(VT_TOPIC); }
  const testtable *auth() const { return GetPointer<const testtable *>(VT_AUTH); }
  const flatbuffers::String *name() const { return GetPointer<const flatbuffers::String *>(VT_NAME); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int64_t>(verifier, VT_HOST) &&
           VerifyField<int32_t>(verifier, VT_PORT) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_TOPIC) &&
           verifier.Verify(topic()) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_AUTH) &&
           verifier.VerifyTable(auth()) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, VT_NAME) &&
           verifier.Verify(name()) &&
           verifier.EndTable();
  }
};

struct test2Builder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_host(int64_t host) { fbb_.AddElement<int64_t>(test2::VT_HOST, host, 0); }
  void add_port(int32_t port) { fbb_.AddElement<int32_t>(test2::VT_PORT, port, 0); }
  void add_topic(flatbuffers::Offset<flatbuffers::String> topic) { fbb_.AddOffset(test2::VT_TOPIC, topic); }
  void add_auth(flatbuffers::Offset<testtable> auth) { fbb_.AddOffset(test2::VT_AUTH, auth); }
  void add_name(flatbuffers::Offset<flatbuffers::String> name) { fbb_.AddOffset(test2::VT_NAME, name); }
  test2Builder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  test2Builder &operator=(const test2Builder &);
  flatbuffers::Offset<test2> Finish() {
    auto o = flatbuffers::Offset<test2>(fbb_.EndTable(start_, 5));
    return o;
  }
};

inline flatbuffers::Offset<test2> Createtest2(flatbuffers::FlatBufferBuilder &_fbb,
   int64_t host = 0,
   int32_t port = 0,
   flatbuffers::Offset<flatbuffers::String> topic = 0,
   flatbuffers::Offset<testtable> auth = 0,
   flatbuffers::Offset<flatbuffers::String> name = 0) {
  test2Builder builder_(_fbb);
  builder_.add_host(host);
  builder_.add_name(name);
  builder_.add_auth(auth);
  builder_.add_topic(topic);
  builder_.add_port(port);
  return builder_.Finish();
}

inline const Mqtt::test2 *Gettest2(const void *buf) { return flatbuffers::GetRoot<Mqtt::test2>(buf); }

inline bool Verifytest2Buffer(flatbuffers::Verifier &verifier) { return verifier.VerifyBuffer<Mqtt::test2>(); }

inline void Finishtest2Buffer(flatbuffers::FlatBufferBuilder &fbb, flatbuffers::Offset<Mqtt::test2> root) { fbb.Finish(root); }

}  // namespace Mqtt

#endif  // FLATBUFFERS_GENERATED_SERVERLOGIN11_MQTT_H_
